# Generated by Django 2.1.7 on 2023-04-18 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='image',
        ),
        migrations.AddField(
            model_name='chat',
            name='person',
            field=models.CharField(max_length=200, null='True'),
            preserve_default='True',
        ),
    ]
